(function(){
  const list = document.getElementById('subject-list');
  const subjects = [
    '01_PHYSICS','02_CHEMISTRY','03_BIOLOGY','04_MATHEMATICS','05_ENVIRONMENTAL_SCIENCE',
    '06_ICT_FUNDAMENTALS','07_WEB_DEVELOPMENT','08_BACKEND_DEVELOPMENT','09_DATABASE_SQL','10_NETWORKING_INTERNET',
    '11_CYBERSECURITY','12_OPERATING_SYSTEMS_HARDWARE','13_ARTIFICIAL_INTELLIGENCE','14_MACHINE_LEARNING','15_DATA_SCIENCE_STATISTICS',
    '16_ELECTRICAL_ENGINEERING','17_MECHANICAL_ENGINEERING','18_CIVIL_ENGINEERING','19_ELECTRONICS_ROBOTICS','20_RENEWABLE_ENERGY_GREEN_TECH',
    '21_ASTRONOMY_SPACE_SCIENCE','22_GEOLOGY_EARTH_SCIENCE','23_HUMAN_ANATOMY_HEALTH','24_GENETICS_BIOTECHNOLOGY','25_STATISTICS_PROBABILITY',
    '26_GEOMETRY_TRIGONOMETRY','27_CALCULUS_ANALYSIS','28_DISCRETE_MATH_LOGIC'
  ];

  subjects.forEach(s => {
    const li = document.createElement('li');
    li.textContent = s.replace(/_/g,' ');
    list.appendChild(li);
  });
})();