/**
 * Default numbered parts per specimen.
 * `target` snaps the pin to a named node/mesh after load.
 * `position` is local XYZ on the normalized model (used when there is no target, or after a hand edit).
 * After the user drags a pin we set `pinned: true` so it stops re-snapping.
 */
function pin(n, id, enT, bnT, enB, bnB, extra = {}) {
  return {
    id,
    n,
    title: { en: enT, bn: bnT },
    body: { en: enB, bn: bnB },
    ...extra,
  };
}

export const DEFAULT_PINS = {
  "animal-cell": [
    pin(1, "membrane", "Plasma membrane", "প্লাজমা ঝিল্লি",
      "The outer skin of the cell. It controls what enters and leaves.",
      "কোষের বাইরের আবরণ। কী ঢুকবে আর কী বেরোবে তা নিয়ন্ত্রণ করে।",
      { target: "Sphere.001", pinned: true, position: [-2.2545, -0.0451, 2.4627] }),
    pin(2, "nucleus", "Nucleus", "নিউক্লিয়াস",
      "Holds the DNA. This is the cell's control centre.",
      "ডিএনএ এখানে থাকে। কোষের নিয়ন্ত্রণ কেন্দ্র।",
      { target: "Sphere.002", pinned: true, position: [-0.9876, 0.1796, -0.4452] }),
    pin(3, "nucleolus", "Nucleolus", "নিউক্লিওলাস",
      "A dense spot inside the nucleus that builds ribosome parts.",
      "নিউক্লিয়াসের ভেতরের ঘন অংশ - রাইবোসোমের টুকরো তৈরি হয়।",
      { target: "Icosphere", pinned: true, position: [-0.3518, 0.4361, -0.4716] }),
    pin(4, "er", "Endoplasmic reticulum", "এন্ডোপ্লাজমিক রেটিকুলাম",
      "Folded membranes that make and move proteins and lipids.",
      "ভাঁজ করা ঝিল্লি - প্রোটিন ও লিপিড তৈরি ও সরবরাহ করে।",
      { target: "BezierCurve", pinned: true, position: [-0.6075, -0.0886, 0.8965] }),
    pin(5, "golgi", "Golgi apparatus", "গলজি যন্ত্র",
      "Packs proteins into vesicles and ships them where they need to go.",
      "প্রোটিন প্যাক করে ভেসিকেলে পাঠায় যেখানে দরকার।",
      { target: "BezierCurve.002", pinned: true, position: [1.1350, -0.5142, 1.8612] }),
    pin(6, "cytoplasm", "Cytoplasm", "সাইটোপ্লাজম",
      "The jelly the organelles sit in. Most chemistry of the cell happens here.",
      "অঙ্গাণু যে জেলির মধ্যে ভাসে। কোষের বেশির ভাগ রাসায়নিক কাজ এখানে।",
      { target: "Sphere", pinned: true, position: [-2.5346, -0.0650, -1.2124] }),
    pin(7, "mito", "Mitochondrion", "মাইটোকন্ড্রিয়া",
      "Breaks down fuel to make ATP - the cell's usable energy.",
      "খাদ্য ভেঙে ATP তৈরি করে - কোষের ব্যবহারযোগ্য শক্তি।",
      { target: "Roundcube", pinned: true, position: [-0.3516, 0.1489, 3.1659] }),
    pin(8, "lysosome", "Lysosome", "লাইসোসোম",
      "A bag of digestive enzymes. It recycles worn-out parts.",
      "হজমকারী এনজাইমের থলি। পুরনো অংশ পুনর্ব্যবহার করে।",
      { target: "Roundcube.000", pinned: true, position: [-0.7619, 0.0984, 2.3410] }),
    pin(9, "vacuole", "Vesicle", "ভেসিকল",
      "A small transport bubble moving material through the cell.",
      "কোষের ভেতর মালামাল সরানোর ছোট বুদবুদ।",
      { target: "Roundcube.001", pinned: true, position: [0.0155, -0.1884, 2.0675] }),
    pin(10, "centrosome", "Centrosome", "সেন্ট্রোসোম",
      "Organises microtubules. Important when the cell divides.",
      "মাইক্রোটিউবিউল সাজায়। কোষ বিভাজনে দরকারি।",
      { target: "Icosphere.002", pinned: true, position: [1.8026, -0.0735, 0.5169] }),
  ],

  "plant-cell": [
    pin(1, "wall", "Cell wall", "কোষপ্রাচীর",
      "A rigid cellulose coat. It keeps the plant cell's shape.",
      "শক্ত সেলুলোজ আবরণ। উদ্ভিদকোষের আকৃতি ধরে রাখে।",
      { target: "cell_wall", pinned: true, position: [3.2598, 0.7290, 2.4996] }),
    pin(2, "membrane", "Plasma membrane", "প্লাজমা ঝিল্লি",
      "The lipid bilayer just inside the wall.",
      "প্রাচীরের ঠিক ভেতরের লিপিড বাইলেয়ার।",
      { target: "lipid_bilayer", pinned: true, position: [7.9364, 0.9546, 4.3964] }),
    pin(3, "nucleus", "Nucleus", "নিউক্লিয়াস",
      "Contains the DNA that runs the cell.",
      "কোষ চালানোর ডিএনএ এখানে।",
      { target: "Nucleus_2", pinned: true, position: [7.6280, 0.9247, -1.8793] }),
    pin(4, "nucleolus", "Nucleolus", "নিউক্লিওলাস",
      "Makes ribosomal RNA inside the nucleus.",
      "নিউক্লিয়াসের ভেতর রাইবোসোমাল আরএনএ তৈরি করে।",
      { target: "Nucleolus_2", pinned: true, position: [7.3494, 3.2817, -0.4486] }),
    pin(5, "vacuole", "Central vacuole", "কেন্দ্রীয় ভ্যাকুওল",
      "A large water store. Turgor here keeps the plant upright.",
      "বড় পানির ভাণ্ডার। এখানকার চাপ গাছকে সোজা রাখে।",
      { target: "central_vacuole", pinned: true, position: [7.2481, 0.5942, 1.3846] }),
    pin(6, "er", "Endoplasmic reticulum", "এন্ডোপ্লাজমিক রেটিকুলাম",
      "Rough and smooth ER - protein and lipid workshop.",
      "রাফ ও স্মুথ ইআর - প্রোটিন ও লিপিডের কারখানা।",
      { target: "rough_smooth_er", pinned: true, position: [7.8302, 0.1975, -0.6709] }),
    pin(7, "golgi", "Golgi apparatus", "গলজি যন্ত্র",
      "Finishes and ships molecules made in the ER.",
      "ইআর-এ তৈরি অণু শেষ করে পাঠায়।",
      { target: "golgi", pinned: true, position: [5.0523, -0.0325, 1.3643] }),
    pin(8, "chloro", "Chloroplast", "ক্লোরোপ্লাস্ট",
      "Green plastids that run photosynthesis.",
      "সালোকসংশ্লেষ চালানো সবুজ প্লাস্টিড।",
      { target: "Icosphere", pinned: true, position: [8.3380, 0.1784, 1.8595] }),
    pin(9, "lyso", "Lysosome", "লাইসোসোম",
      "Breaks down waste inside the cell.",
      "কোষের ভেতরের বর্জ্য ভাঙে।",
      { target: "Lysosomes", pinned: true, position: [9.6915, -0.0325, 0.3858] }),
    pin(10, "ribo", "Ribosomes", "রাইবোসোম",
      "Tiny protein factories floating in the cytosol.",
      "সাইটোসলে ভাসতে থাকা ক্ষুদ্র প্রোটিন কারখানা।",
      { target: "floating_ribosomes", pinned: true, position: [6.6807, 0.2725, 3.0410] }),
    pin(11, "cyto", "Cytoskeleton", "সাইটোস্কেলিটন",
      "Protein filaments that support and move the cell interior.",
      "প্রোটিন ফিলামেন্ট - ভেতরের অংশ ধরে ও নাড়ায়।",
      { target: "cytoskeleton", pinned: true, position: [8.5516, -0.0325, 0.4759] }),
    pin(12, "chromatin", "Chromatin", "ক্রোমাটিন",
      "DNA wrapped on proteins, visible in the nucleus.",
      "প্রোটিনে জড়ানো ডিএনএ - নিউক্লিয়াসে দেখা যায়।",
      { target: "chromatin", pinned: true, position: [5.5116, 1.7586, -0.0540] }),
  ],

  neuron: [
    pin(1, "soma", "Soma (cell body)", "সোমা (কোষদেহ)",
      "The metabolic centre. The nucleus sits here.",
      "বিপাকের কেন্দ্র। নিউক্লিয়াস এখানে।",
      { target: "Soma" }),
    pin(2, "nucleus", "Nucleus", "নিউক্লিয়াস",
      "Holds the neuron’s DNA.",
      "নিউরনের ডিএনএ এখানে।",
      { target: "NucleusOuter" }),
    pin(3, "dendrite", "Dendrites", "ডেনড্রাইট",
      "Branching inputs. They collect signals from other neurons.",
      "শাখা-প্রশাখা ইনপুট। অন্য নিউরন থেকে সংকেত নেয়।",
      { target: "Dendrite_d0" }),
    pin(4, "myelin", "Myelin sheath", "মায়েলিন আবরণ",
      "Fatty wrap that speeds the impulse along the axon.",
      "চর্বির আবরণ - অ্যাক্সনে আবেগ দ্রুত চালায়।",
      { target: "Myelin" }),
    pin(5, "ranvier", "Node of Ranvier", "রানভিয়ারের পর্ব",
      "Gaps in myelin. The impulse jumps from node to node.",
      "মায়েলিনের ফাঁক। আবেগ পর্ব থেকে পর্বে লাফায়।",
      { target: "NodeRanvier" }),
    pin(6, "terminal", "Axon terminal", "অ্যাক্সন প্রান্ত",
      "The output end. It talks to the next cell at a synapse.",
      "আউটপুট প্রান্ত। সাইন্যাপসে পরের কোষের সাথে কথা বলে।",
      { target: "AxonTerminal" }),
    pin(7, "bulb", "Synaptic bulb", "সাইন্যাপটিক বাল্ব",
      "Swollen tip that releases neurotransmitter.",
      "ফোলা প্রান্ত - নিউরোট্রান্সমিটার ছাড়ে।",
      { target: "SynapticBulb" }),
    pin(8, "golgi", "Golgi apparatus", "গলজি যন্ত্র",
      "Packages proteins inside the soma.",
      "সোমার ভেতর প্রোটিন প্যাক করে।",
      { target: "Golgi" }),
    pin(9, "rer", "Rough ER", "রাফ ইআর",
      "Ribosome-studded membranes - protein synthesis.",
      "রাইবোসোম-লাগানো ঝিল্লি - প্রোটিন সংশ্লেষ।",
      { target: "RoughER" }),
    pin(10, "ser", "Smooth ER", "স্মুথ ইআর",
      "Makes lipids and helps with calcium storage.",
      "লিপিড তৈরি ও ক্যালসিয়াম ভাণ্ডার।",
      { target: "SmoothER" }),
    pin(11, "mito", "Mitochondria", "মাইটোকন্ড্রিয়া",
      "ATP supply for firing and recovery.",
      "স্পাইক ও পুনরুদ্ধারের জন্য ATP।",
      { target: "Mito" }),
    pin(12, "ribo", "Free ribosomes", "মুক্ত রাইবোসোম",
      "Make proteins that stay in the cytosol.",
      "সাইটোসলে থাকা প্রোটিন তৈরি করে।",
      { target: "FreeRibosome" }),
  ],

  coronavirus: [
    pin(1, "envelope", "Envelope", "আবরণ",
      "A lipid membrane stolen from the host cell.",
      "হোস্ট কোষ থেকে নেওয়া লিপিড ঝিল্লি।",
      { position: [0, 0, 0] }),
    pin(2, "spike", "Spike protein", "স্পাইক প্রোটিন",
      "The club-shaped protein that docks on human cells.",
      "মানবকোষে লাগার ক্লাব-আকৃতির প্রোটিন।",
      { position: [0, 0.85, 0.35] }),
    pin(3, "spike2", "Spike (far side)", "স্পাইক (অন্য পাশ)",
      "Spikes cover the whole particle, not just one face.",
      "স্পাইক পুরো কণা জুড়ে - শুধু এক পাশে নয়।",
      { position: [-0.7, -0.2, -0.55] }),
    pin(4, "core", "Core", "কেন্দ্র",
      "Inside: RNA genome and nucleoproteins.",
      "ভেতরে: আরএনএ জিনোম ও নিউক্লিওপ্রোটিন।",
      { position: [0.15, -0.1, 0.1] }),
  ],

  dna: [
    pin(1, "helix", "Double helix", "ডাবল হেলিক্স",
      "Two strands twist around a common axis.",
      "দুই সূত্র এক অক্ষ ঘিরে পাক খায়।",
      { position: [0, 0.4, 0] }),
    pin(2, "backbone", "Sugar-phosphate backbone", "সুগার-ফসফেট ব্যাকবোন",
      "The rails of the ladder - strong covalent chain.",
      "মইয়ের রেলিং - শক্ত কোভ্যালেন্ট শিকল।",
      { position: [0.35, 0, 0.15] }),
    pin(3, "bases", "Base pairs", "ক্ষারক জোড়",
      "A-T and C-G rungs. Sequence here is the genetic code.",
      "A-T ও C-G ধাপ। এখানকার ক্রমই জিনগত সংকেত।",
      { position: [0, 0, 0] }),
    pin(4, "end", "Strand end", "সূত্রের প্রান্ত",
      "DNA strands have direction: 5′ to 3′.",
      "ডিএনএ সূত্রের দিক আছে: ৫′ থেকে ৩′।",
      { position: [0, -0.85, 0] }),
  ],

  heart: [
    pin(1, "ra", "Right atrium", "ডান অলিন্দ",
      "Receives deoxygenated blood from the body.",
      "দেহ থেকে অক্সিজেন-কমা রক্ত নেয়।",
      { pinned: true, position: [0.0092, 0.5720, 0.2407] }),
    pin(2, "rv", "Right ventricle", "ডান নিলয়",
      "Pumps that blood to the lungs.",
      "সেই রক্ত ফুসফুসে পাঠায়।",
      { pinned: true, position: [0.1367, 0.3258, 0.2583] }),
    pin(3, "la", "Left atrium", "বাম অলিন্দ",
      "Receives oxygen-rich blood from the lungs.",
      "ফুসফুস থেকে অক্সিজেন-সমৃদ্ধ রক্ত নেয়।",
      { pinned: true, position: [0.2049, 0.5237, -0.0429] }),
    pin(4, "lv", "Left ventricle", "বাম নিলয়",
      "The thick-walled pump that drives the systemic circuit.",
      "মোটা দেয়ালের পাম্প - সারা দেহে রক্ত পাঠায়।",
      { pinned: true, position: [0.2643, 0.3000, 0.0117] }),
    pin(5, "aorta", "Aorta", "মহাধমনি",
      "The main artery leaving the left ventricle.",
      "বাম নিলয় থেকে বেরোনো প্রধান ধমনি।",
      { pinned: true, position: [-0.0246, 0.8639, 0.1555] }),
    pin(6, "pa", "Pulmonary artery", "ফুসফুসীয় ধমনি",
      "Carries blood from the right ventricle to the lungs.",
      "ডান নিলয় থেকে ফুসফুসে রক্ত নিয়ে যায়।",
      { pinned: true, position: [0.0931, 0.6816, -0.1071] }),
    pin(7, "svc", "Superior vena cava", "উচ্চ মহাশিরা",
      "Returns blood from the head and arms to the right atrium.",
      "মাথা ও হাত থেকে রক্ত ডান অলিন্দে ফেরায়।",
      { pinned: true, position: [-0.0188, 0.9171, -0.0313] }),
    pin(8, "apex", "Apex", "শীর্ষ",
      "The pointed bottom of the heart, mostly left ventricle.",
      "হৃৎপিণ্ডের নিচের ডগা - বেশির ভাগই বাম নিলয়।",
      { pinned: true, position: [0.2221, 0.0522, 0.0284] }),
  ],

  brain: [
    pin(1, "frontal", "Frontal lobe", "ফ্রন্টাল লোব",
      "Planning, movement, some language. Behind the forehead.",
      "পরিকল্পনা, চলাচল, কিছু ভাষা। কপালের পেছনে।",
      { position: [0, 0.15, 0.85] }),
    pin(2, "parietal", "Parietal lobe", "প্যারাইটাল লোব",
      "Touch, space, and putting senses together.",
      "স্পর্শ, স্থান এবং ইন্দ্রিয় জোড়া লাগানো।",
      { position: [0, 0.55, 0.1] }),
    pin(3, "temporal", "Temporal lobe", "টেম্পোরাল লোব",
      "Hearing, memory, and recognising things.",
      "শ্রবণ, স্মৃতি ও চেনা।",
      { position: [0.75, -0.15, 0.15] }),
    pin(4, "occipital", "Occipital lobe", "অক্সিপিটাল লোব",
      "Vision. At the back of the cerebrum.",
      "দৃষ্টি। সেরিব্রামের পেছনে।",
      { position: [0, 0.2, -0.85] }),
    pin(5, "cerebellum", "Cerebellum", "সেরিবেলাম",
      "Timing and coordination of movement. Under the occipital lobe.",
      "নড়ার সময় ও সমন্বয়। অক্সিপিটাল লোবের নিচে।",
      { position: [0, -0.55, -0.55] }),
    pin(6, "brainstem", "Brainstem", "ব্রেইনস্টেম",
      "Connects brain to spinal cord. Breathing and heart rate live here.",
      "মস্তিষ্ককে সুষুম্নাকাণ্ডে যোড়ে। শ্বাস ও হৃদস্পন্দন এখানে।",
      { position: [0, -0.85, -0.15] }),
  ],

  lungs: [
    pin(1, "right", "Right lung", "ডান ফুসফুস",
      "Three lobes. Slightly larger than the left.",
      "তিন লোব। বামের চেয়ে একটু বড়।",
      { target: "lungh_part01" }),
    pin(2, "left", "Left lung", "বাম ফুসফুস",
      "Two lobes, with a notch for the heart.",
      "দুই লোব - হৃৎপিণ্ডের জন্য একটি খাঁজ।",
      { target: "lungh_part02" }),
  ],

  kidney: [
    pin(1, "cortex", "Cortex", "কর্টেক্স",
      "Outer layer. Many glomeruli filter blood here.",
      "বাইরের স্তর। অনেক গ্লোমেরুলাস এখানে রক্ত ছাঁকে।",
      { target: "Plane_Material", pinned: true, position: [22.9949, -8.5218, 251.3140] }),
    pin(2, "medulla", "Medulla", "মেডুলা",
      "Inner pyramids that concentrate urine.",
      "ভেতরের পিরামিড - প্রস্রাব ঘন করে।",
      { target: "Plane.001", pinned: true, position: [20.6451, -7.6618, 249.2564] }),
    pin(3, "pelvis", "Renal pelvis", "বৃক্কীয় পেলভিস",
      "Collects urine and passes it to the ureter.",
      "প্রস্রাব জমিয়ে ইউরেটারে পাঠায়।",
      { target: "Plane.002", pinned: true, position: [7.7497, 3.1284, 251.1801] }),
    pin(4, "artery", "Renal vessel", "বৃক্কীয় রক্তনালি",
      "Blood in and out of the kidney.",
      "বৃক্কে রক্ত আসা-যাওয়া।",
      { target: "Cylinder", pinned: true, position: [5.0733, 4.1024, 251.1061] }),
    pin(5, "ureter", "Ureter", "ইউরেটার",
      "Tube toward the bladder.",
      "মূত্রাশয়ের দিকে নালি।",
      { target: "Cylinder.001", pinned: true, position: [18.0717, -0.2676, 251.1273] }),
  ],

  nephron: [
    pin(1, "glom", "Glomerulus", "গ্লোমেরুলাস",
      "Capillary knot that filters blood.",
      "রক্ত ছাঁকার কৈশিক জট।",
      { target: "Sphere" }),
    pin(2, "bowman", "Bowman’s capsule", "বোম্যানের ক্যাপসুল",
      "Cup around the glomerulus that catches the filtrate.",
      "গ্লোমেরুলাস ঘিরে থাকা কাপ - ফিলট্রেট ধরে।",
      { target: "Sphere.001" }),
    pin(3, "tubule", "Tubule", "নালিকা",
      "Reabsorbs water and useful solutes.",
      "পানি ও দরকারি দ্রব পুনঃশোষণ করে।",
      { target: "Cylinder.002" }),
    pin(4, "loop", "Loop region", "লুপ অঞ্চল",
      "The dip that helps concentrate urine.",
      "প্রস্রাব ঘন করতে সাহায্য করা ভাঁজ।",
      { target: "Cylinder.009" }),
    pin(5, "collect", "Collecting path", "সংগ্রহ পথ",
      "Filtrate heading toward the pelvis.",
      "পেলভিসের দিকে যাওয়া ফিলট্রেট।",
      { target: "Cylinder.005" }),
  ],

  mouth: [
    pin(1, "lips", "Lips", "ওষ্ঠ",
      "Entry to the oral cavity.",
      "মুখগহ্বরের প্রবেশ।",
      { position: [0, 0.15, 0.7] }),
    pin(2, "teeth", "Teeth", "দাঁত",
      "Cut and grind food before swallowing.",
      "গিলার আগে খাবার কাটে ও পেষে।",
      { position: [0, 0.05, 0.25] }),
    pin(3, "tongue", "Tongue", "জিহ্বা",
      "Taste and speech. Pushes the bolus back.",
      "স্বাদ ও কথা। খাদ্যপিণ্ড পেছনে ঠেলে।",
      { position: [0, -0.35, 0.05] }),
    pin(4, "palate", "Palate", "তালু",
      "Roof of the mouth - hard in front, soft behind.",
      "মুখের ছাদ - সামনে শক্ত, পেছনে নরম।",
      { position: [0, 0.45, -0.15] }),
  ],

  earth: [
    pin(1, "npole", "North Pole", "উত্তর মেরু",
      "Axis point in the Arctic.",
      "আর্কটিকের অক্ষবিন্দু।",
      { position: [0, 1.05, 0] }),
    pin(2, "spole", "South Pole", "দক্ষিণ মেরু",
      "Axis point on Antarctica.",
      "অ্যান্টার্কটিকার অক্ষবিন্দু।",
      { position: [0, -1.05, 0] }),
    pin(3, "eq", "Equator", "নিরক্ষরেখা",
      "0° latitude. Earth is widest here.",
      "০° অক্ষাংশ। এখানে পৃথিবী সবচেয়ে চওড়া।",
      { position: [1.05, 0, 0] }),
    pin(4, "africa", "Africa (approx.)", "আফ্রিকা (আনুমানিক)",
      "Drag this pin onto Africa if the texture is rotated.",
      "টেক্সচার ঘোরানো থাকলে পিনটি আফ্রিকায় টেনে নিন।",
      { position: [0.2, 0.1, 0.95] }),
    pin(5, "asia", "Asia (approx.)", "এশিয়া (আনুমানিক)",
      "Largest continent. Move the pin onto the landmass.",
      "সবচেয়ে বড় মহাদেশ। পিনটি স্থলভাগে সরিয়ে নিন।",
      { position: [0.7, 0.45, 0.4] }),
  ],

  moon: [
    pin(1, "nearside", "Near side", "নিকট পার্শ্ব",
      "The face locked toward Earth. Dark maria sit here.",
      "পৃথিবীর দিকে তাক করা মুখ। অন্ধকার মারে এখানে।",
      { position: [0, 0, 1.05] }),
    pin(2, "farside", "Far side", "দূর পার্শ্ব",
      "Never faces Earth. Heavily cratered, few maria.",
      "পৃথিবীর দিকে তাকায় না। বেশি খাদ, কম মারে।",
      { position: [0, 0, -1.05] }),
    pin(3, "npole", "North Pole", "উত্তর মেরু",
      "Permanently shadowed craters may hold ice.",
      "স্থায়ী ছায়াযুক্ত খাদে বরফ থাকতে পারে।",
      { position: [0, 1.05, 0] }),
    pin(4, "spole", "South Pole", "দক্ষিণ মেরু",
      "Target of several landing missions.",
      "কয়েকটি অবতরণ মিশনের লক্ষ্য।",
      { position: [0, -1.05, 0] }),
  ],

  iss: [
    pin(1, "core", "Station core", "স্টেশনের কেন্দ্র",
      "Pressurised modules where the crew lives and works.",
      "চাপযুক্ত মডিউল - ক্রু এখানে থাকে ও কাজ করে।",
      { position: [0, 0, 0] }),
    pin(2, "truss", "Truss", "ট্রাস",
      "The long backbone that holds the solar arrays.",
      "লম্বা মেরুদণ্ড - সোলার অ্যারে ধরে।",
      { position: [0.9, 0, 0] }),
    pin(3, "solar", "Solar arrays", "সোলার অ্যারে",
      "Gold-blue wings that power the station.",
      "স্টেশনের বিদ্যুৎ - সোনালি-নীল ডানা।",
      { position: [0, 0.15, 0.7] }),
    pin(4, "radiator", "Radiators", "রেডিয়েটর",
      "White panels that dump heat to space.",
      "সাদা প্যানেল - তাপ মহাকাশে ছাড়ে।",
      { position: [0, -0.2, -0.45] }),
  ],

  falcon9: [
    pin(1, "capsule", "Dragon capsule", "ড্রাগন ক্যাপসুল",
      "Crew compartment at the top.",
      "উপরে ক্রু কক্ষ।",
      { target: "nosecone" }),
    pin(2, "windows", "Crew windows", "ক্রু জানালা",
      "Windows on the capsule.",
      "ক্যাপসুলের জানালা।",
      { target: "windows" }),
    pin(3, "heat", "Heat shield", "হিট শিল্ড",
      "Ablative shield for re-entry.",
      "পুনঃপ্রবেশের অ্যাবলেটিভ ঢাল।",
      { target: "heatshield" }),
    pin(4, "trunk", "Trunk", "ট্রাঙ্ক",
      "Unpressurised cargo section behind Dragon.",
      "ড্রাগনের পেছনের চাপহীন মালামাল অংশ।",
      { target: "trunk" }),
    pin(5, "stage", "First stage", "প্রথম স্টেজ",
      "The booster that lands back on Earth.",
      "বুস্টার যা পৃথিবীতে ফিরে অবতরণ করে।",
      { target: "body" }),
    pin(6, "legs", "Landing legs", "ল্যান্ডিং লেগ",
      "Four legs that unfold for landing.",
      "অবতরণে খুলে যাওয়া চারটি পা।",
      { target: "leg" }),
    pin(7, "fins", "Grid fins", "গ্রিড ফিন",
      "Steer the booster on the way down.",
      "নামার সময় বুস্টার ঘোরায়।",
      { target: "grid fin waffle" }),
    pin(8, "engines", "Engine cluster", "ইঞ্জিন গুচ্ছ",
      "Merlin engines at the octaweb.",
      "অক্টাওয়েবে মার্লিন ইঞ্জিন।",
      { target: "octaweb" }),
    pin(9, "dock", "Docking port", "ডকিং পোর্ট",
      "Where Dragon meets the station.",
      "ড্রাগন যেখানে স্টেশনের সাথে জোড়ে।",
      { target: "docking" }),
  ],

  atom: [
    pin(1, "nucleus", "Nucleus", "নিউক্লিয়াস",
      "Protons and neutrons packed in the centre.",
      "কেন্দ্রে প্রোটন ও নিউট্রন জমা।",
      { position: [0, 0, 0] }),
    pin(2, "cloud", "Electron cloud", "ইলেকট্রন মেঘ",
      "Electrons occupy regions of space, not little rings.",
      "ইলেকট্রন ছোট বলয় নয় - জায়গার অঞ্চল দখল করে।",
      { position: [0.7, 0.2, 0.4] }),
    pin(3, "shell", "Outer region", "বাইরের অঞ্চল",
      "Valence electrons here decide bonding.",
      "এখানকার ভ্যালেন্স ইলেকট্রন বন্ধন ঠিক করে।",
      { position: [-0.55, 0.45, -0.35] }),
  ],

  "atomic-models": [
    pin(1, "kit", "Model kit", "মডেল কিট",
      "Ball-and-stick classroom atoms. Isolate one piece with a pin.",
      "শ্রেণিকক্ষের বল-স্টিক পরমাণু। একটি টুকরো আলাদা করতে পিন চাপুন।",
      { position: [0, 0.2, 0] }),
    pin(2, "red", "Proton / positive (red)", "প্রোটন / ধনাত্মক (লাল)",
      "Red balls in this kit are the positive pieces.",
      "এই কিটে লাল বলগুলো ধনাত্মক অংশ।",
      { target: "Box056_red" }),
    pin(3, "blue", "Electron / negative (blue)", "ইলেকট্রন / ঋণাত্মক (নীল)",
      "Blue balls mark the negative pieces.",
      "নীল বল ঋণাত্মক অংশ।",
      { target: "Box073_blue" }),
    pin(4, "grey", "Stand", "স্ট্যান্ড",
      "The grey base the models sit on.",
      "মডেল যে ধূসর বেসে দাঁড়ায়।",
      { target: "Box001_grey" }),
  ],

  "wind-turbine": [
    pin(1, "tower", "Nacelle & tower", "ন্যসেল ও টাওয়ার",
      "The body that holds the generator, on top of the tower.",
      "জেনারেটর ধরে রাখা দেহ - টাওয়ারের মাথায়।",
      { target: "Main Unit" }),
    pin(2, "blades", "Rotor blades", "রোটর ব্লেড",
      "Three blades catch the wind and turn the shaft.",
      "তিন ব্লেড বাতাস ধরে শ্যাফট ঘোরায়।",
      { target: "Blades" }),
  ],

  "engine-v8": [
    pin(1, "block", "Engine block", "ইঞ্জিন ব্লক",
      "The main casting that holds the cylinders.",
      "সিলিন্ডার ধরে রাখা মূল কাঠামো।",
      { target: "Cube" }),
    pin(2, "gear", "Timing gear", "টাইমিং গিয়ার",
      "Keeps camshaft and crankshaft in step.",
      "ক্যামশ্যাফট ও ক্র্যাঙ্কশ্যাফট এক তালে রাখে।",
      { target: "Gear" }),
    pin(3, "cyl", "Cylinders", "সিলিন্ডার",
      "Where combustion pushes the pistons.",
      "যেখানে দহন পিস্টন ঠেলে।",
      { target: "Cylinder" }),
    pin(4, "path", "Belt / path", "বেল্ট / পথ",
      "A drive path around the front of the engine.",
      "ইঞ্জিনের সামনে ঘোরা ড্রাইভ পথ।",
      { target: "NurbsPath" }),
  ],

  city: [
    pin(1, "cars", "Cars", "গাড়ি",
      "Low-poly vehicles on the street - mass you can talk about in Force Fighter.",
      "রাস্তার লো-পলি গাড়ি - Force Fighter-এ ভর নিয়ে কথা বলার উপযোগী।",
      { target: "Cars", pinned: true, position: [-663.4454, -62.5012, -973.1096] }),
    pin(2, "lights", "Traffic lights", "ট্রাফিক লাইট",
      "Signals at the junction.",
      "মোড়ের সংকেত।",
      { target: "traffic_light", pinned: true, position: [-547.1169, 154.5918, -218.4438] }),
    pin(3, "floor", "Street / ground", "রাস্তা / মাটি",
      "The ground plane the city sits on.",
      "শহর যে তলে বসে।",
      { target: "Floor", pinned: true, position: [-544.2376, -118.8298, 491.0286] }),
    pin(4, "house", "House", "বাড়ি",
      "Where people live.",
      "মানুষ যেখানে থাকে।",
      { pinned: true, position: [45.3039, 335.2490, 181.7419] }),
  ],

  multimeter: [
    pin(1, "body", "Body", "বডি",
      "The meter housing.",
      "মিটারের খোল।",
      { target: "mm1_0" }),
    pin(2, "glass", "Window", "জানালা",
      "Clear cover over the scale.",
      "স্কেলের উপর স্বচ্ছ ঢাকনা।",
      { target: "mm1kaca" }),
    pin(3, "scale", "Scale", "স্কেল",
      "Printed ranges for volts, amps and ohms.",
      "ভোল্ট, অ্যাম্পিয়ার ও ওহমের রেঞ্জ।",
      { target: "mm1skala" }),
    pin(4, "knob", "Range knob", "রেঞ্জ নব",
      "Selects what the meter is measuring.",
      "মিটার কী মাপবে তা বেছে নেয়।",
      { target: "pemutar" }),
    pin(5, "needle", "Needle", "কাঁটা",
      "The analog pointer.",
      "অ্যানালগ নির্দেশক।",
      { target: "jarum" }),
  ],

  ammeter: [
    pin(1, "body", "Meter body", "মিটার বডি",
      "Analog ammeter housing and scale.",
      "অ্যানালগ অ্যামিটারের খোল ও স্কেল।",
      { target: "Main1_L" }),
    pin(2, "btn1", "Range button", "রেঞ্জ বোতাম",
      "One of the front buttons.",
      "সামের বোতামগুলোর একটি।",
      { target: "Button1_L" }),
    pin(3, "btn2", "Hold / extra button", "অতিরিক্ত বোতাম",
      "Second control on the face.",
      "সামনের দ্বিতীয় নিয়ন্ত্রণ।",
      { target: "Button2_L" }),
    pin(4, "jack", "Input jacks", "ইনপুট জ্যাক",
      "Where the probe plugs in.",
      "প্রোব যেখানে লাগে।",
      { target: "Parts1_L" }),
    pin(5, "cable-a", "Probe cable A", "প্রোব তার ক",
      "One test lead.",
      "একটি টেস্ট লিড।",
      { target: "Cable1_L" }),
    pin(6, "cable-b", "Probe cable B", "প্রোব তার খ",
      "The return lead.",
      "রিটার্ন লিড।",
      { target: "Cable2_L" }),
  ],

  caliper: [
    pin(1, "fixed", "Fixed jaw", "স্থির জো",
      "The stationary measuring face.",
      "মাপার স্থির মুখ।",
      { target: "#TOL0002_Stationary" }),
    pin(2, "move", "Sliding jaw", "স্লাইডিং জো",
      "Moves along the beam to close on the object.",
      "বস্তুতে লাগতে বিমের উপর সরে।",
      { target: "#TOL0002_Movable" }),
    pin(3, "display", "Digital display", "ডিজিটাল ডিসপ্লে",
      "Shows the reading in millimetres or inches.",
      "মিলিমিটার বা ইঞ্চিতে পাঠ দেখায়।",
      { target: "#TOL0002_Display" }),
    pin(4, "glass", "Display window", "ডিসপ্লে জানালা",
      "Cover over the LCD.",
      "এলসিডির ঢাকনা।",
      { target: "#TOL0002_Glass" }),
    pin(5, "wheel", "Thumb wheel", "থাম্ব হুইল",
      "Fine adjustment of the sliding jaw.",
      "স্লাইডিং জোর সূক্ষ্ম সরানো।",
      { target: "#TOL0002_Wheel" }),
  ],

  compass: [
    pin(1, "housing", "Housing", "হাউজিং",
      "The box that holds the compass.",
      "কম্পাস যে বাক্সে থাকে।",
      { position: [0, -0.2, 0] }),
    pin(2, "needle", "Needle", "কাঁটা",
      "Magnetised pointer that seeks north.",
      "উত্তর খোঁজা চুম্বকিত নির্দেশক।",
      { position: [0, 0.35, 0.15] }),
    pin(3, "dial", "Card / dial", "ডায়াল",
      "Degree markings around the needle.",
      "কাঁটার চারপাশের ডিগ্রি দাগ।",
      { position: [0.45, 0.15, 0] }),
  ],

  abacus: [
    pin(1, "frame", "Frame", "ফ্রেম",
      "The wooden (or plastic) rectangle.",
      "কাঠ বা প্লাস্টিকের আয়তক্ষেত্র।",
      { target: "Cube" }),
    pin(2, "rod", "Rod", "দণ্ড",
      "A wire the beads slide on. Each rod is a place value.",
      "গুটি যে তারের উপর সরে। প্রতি দণ্ড একটি স্থানীয় মান।",
      { target: "Cylinder" }),
    pin(3, "bead", "Beads", "গুটি",
      "Counters. Slide them to represent a number.",
      "গণনার গুটি। সংখ্যা দেখাতে সরান।",
      { target: "Sphere" }),
  ],

  calculator: [
    pin(1, "body", "Body", "বডি",
      "The case of the mechanical calculator.",
      "যান্ত্রিক ক্যালকুলেটরের খোল।",
      { target: "Plane" }),
    pin(2, "keys", "Keys / drums", "কি / ড্রাম",
      "Input mechanism.",
      "ইনপুট যন্ত্র।",
      { target: "Cylinder" }),
    pin(3, "register", "Register", "রেজিস্টার",
      "Where the result shows.",
      "ফল যেখানে দেখায়।",
      { target: "Circle" }),
  ],
};

export function clonePins(modelId) {
  const src = DEFAULT_PINS[modelId] || [];
  return src.map((p) => ({
    ...p,
    title: { ...p.title },
    body: { ...p.body },
    position: p.position ? [...p.position] : undefined,
  }));
}
